# Generated by Django 6.0.2 on 2026-02-13 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SitesWithScores",
            fields=[
                ("site_id", models.IntegerField(primary_key=True, serialize=False)),
                ("site_name", models.CharField(max_length=255)),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("area_sqm", models.IntegerField()),
                (
                    "solar_irradiance_kwh",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "grid_distance_km",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("slope_degrees", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "road_distance_km",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("elevation_m", models.IntegerField()),
                ("land_type", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=100)),
                (
                    "solar_irradiance_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("area_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "grid_distance_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("slope_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "infrastructure_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "total_suitability_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("analysis_timestamp", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sites_with_scores",
                "ordering": ["-total_suitability_score"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AnalysisParameters",
            fields=[
                ("param_id", models.AutoField(primary_key=True, serialize=False)),
                ("parameter_name", models.CharField(max_length=100, unique=True)),
                (
                    "weight_value",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Weight value between 0 and 1",
                        max_digits=4,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "analysis_parameters",
            },
        ),
        migrations.CreateModel(
            name="Sites",
            fields=[
                ("site_id", models.AutoField(primary_key=True, serialize=False)),
                ("site_name", models.CharField(max_length=255)),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("area_sqm", models.IntegerField()),
                (
                    "solar_irradiance_kwh",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average daily solar irradiance in kWh/m²/day",
                        max_digits=4,
                    ),
                ),
                (
                    "grid_distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Distance to nearest power grid in kilometers",
                        max_digits=5,
                    ),
                ),
                (
                    "slope_degrees",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Terrain slope in degrees",
                        max_digits=4,
                    ),
                ),
                (
                    "road_distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Distance to nearest road in kilometers",
                        max_digits=5,
                    ),
                ),
                (
                    "elevation_m",
                    models.IntegerField(
                        help_text="Elevation above sea level in meters"
                    ),
                ),
                ("land_type", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sites",
                "indexes": [
                    models.Index(fields=["latitude"], name="sites_latitud_2e1968_idx"),
                    models.Index(fields=["longitude"], name="sites_longitu_80de2b_idx"),
                    models.Index(fields=["region"], name="sites_region_d6bd6c_idx"),
                    models.Index(fields=["land_type"], name="sites_land_ty_1f164a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AnalysisResults",
            fields=[
                ("result_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "solar_irradiance_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("area_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "grid_distance_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("slope_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "infrastructure_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "total_suitability_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final weighted score out of 100",
                        max_digits=5,
                    ),
                ),
                ("analysis_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "parameters_snapshot",
                    models.JSONField(
                        blank=True,
                        help_text="JSON snapshot of weights used for this analysis",
                        null=True,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_results",
                        to="sites.sites",
                    ),
                ),
            ],
            options={
                "db_table": "analysis_results",
                "indexes": [
                    models.Index(
                        fields=["total_suitability_score"],
                        name="analysis_re_total_s_4dec8c_idx",
                    ),
                    models.Index(
                        fields=["site"], name="analysis_re_site_id_a4fc6d_idx"
                    ),
                    models.Index(
                        fields=["analysis_timestamp"],
                        name="analysis_re_analysi_a973f3_idx",
                    ),
                ],
            },
        ),
    ]
