# Generated by Django 6.0.2 on 2026-02-11 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisParameters",
            fields=[
                ("param_id", models.AutoField(primary_key=True, serialize=False)),
                ("parameter_name", models.CharField(max_length=100, unique=True)),
                (
                    "weight_value",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Weight value between 0 and 1",
                        max_digits=4,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "analysis_parameters",
            },
        ),
        migrations.AlterField(
            model_name="sites",
            name="grid_distance_km",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Distance to nearest power grid in kilometers",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="sites",
            name="road_distance_km",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Distance to nearest road in kilometers",
                max_digits=5,
            ),
        ),
        migrations.CreateModel(
            name="AnalysisResults",
            fields=[
                ("result_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "solar_irradiance_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("area_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "grid_distance_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("slope_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "infrastructure_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "total_suitability_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final weighted score out of 100",
                        max_digits=5,
                    ),
                ),
                ("analysis_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "parameters_snapshot",
                    models.JSONField(
                        blank=True,
                        help_text="JSON snapshot of weights used for this analysis",
                        null=True,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_results",
                        to="sites.sites",
                    ),
                ),
            ],
            options={
                "db_table": "analysis_results",
                "indexes": [
                    models.Index(
                        fields=["total_suitability_score"],
                        name="analysis_re_total_s_4dec8c_idx",
                    ),
                    models.Index(
                        fields=["site"], name="analysis_re_site_id_a4fc6d_idx"
                    ),
                    models.Index(
                        fields=["analysis_timestamp"],
                        name="analysis_re_analysi_a973f3_idx",
                    ),
                ],
            },
        ),
    ]
