# Generated by Django 6.0.2 on 2026-02-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_analysisparameters_alter_sites_grid_distance_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitesWithScores',
            fields=[
                ('site_id', models.IntegerField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('area_sqm', models.IntegerField()),
                ('solar_irradiance_kwh', models.DecimalField(decimal_places=2, max_digits=4)),
                ('grid_distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slope_degrees', models.DecimalField(decimal_places=2, max_digits=4)),
                ('road_distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('elevation_m', models.IntegerField()),
                ('land_type', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('solar_irradiance_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('area_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grid_distance_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slope_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('infrastructure_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_suitability_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('analysis_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sites_with_scores',
                'ordering': ['-total_suitability_score'],
                'managed': False,
            },
        ),
    ]
